namespace XdtDeviceBridge.Core;

public sealed record InterfaceMonitoringCardDisplay(
    string InterfaceProfileId,
    string InterfaceProfileName,
    string AisName,
    string DeviceName,
    string ExportProfileName,
    string CurrentStatus,
    string StatusClass,
    int ScanIntervalSeconds,
    string ScanIntervalText,
    bool IsScanAnimationActive,
    string LastScanText,
    string AutomaticProcessingText,
    string PatientDisplayText,
    string AisFileName,
    string DeviceFileName,
    string AttachmentFileName,
    string ExportFileName,
    string LastSuccessfulExportText,
    string LastMessage,
    IReadOnlyList<ExpectedInputDisplayItem> ExpectedInputs,
    IReadOnlyList<InterfaceMonitoringDetailItem> FolderDetails,
    string AttachmentImportFolder,
    string AttachmentExportFolder,
    string AttachmentConfigurationStatus,
    bool IsDetailsExpanded = false);
